### ISSUE TITLE
Information on gpuplot library

### ISSUE THREAD

**Issue by qingswu** [pbridger/tensorrt-ssd300-8bit-quantized#1]
Hi there, would you mind sharing some information on the gpuplot library you use in this project? The graph looks fantastic.

**Comment by pbridger** [comment]
Sure! I'm glad you like them :) I'll put them into a library in the coming weeks and write about it, but for now you can take a look at the source - they are pretty easy to use, but not yet very flexible.

**Comment by qingswu** [comment]
oh, my bad, found it in the source code! I tried to search it,  but no luck, lol. Thanks!
